# Generated by Django 5.2.5 on 2025-08-10 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('soft_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=16)),
                ('solver_name', models.CharField(blank=True, max_length=128, null=True)),
                ('input_hash', models.TextField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.term')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='people.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.section')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.timeslot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tenant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timetablerun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'room', 'slot'), name='uniq_run_room_slot'), models.UniqueConstraint(fields=('run', 'prof', 'slot'), name='uniq_run_prof_slot'), models.UniqueConstraint(fields=('run', 'section'), name='uniq_run_section')],
            },
        ),
    ]
