# Generated by Django 5.2.5 on 2025-08-24 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(max_length=128)),
                ('row_id', models.BigIntegerField()),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('INSERT', 'INSERT'),
                            ('UPDATE', 'UPDATE'),
                            ('DELETE', 'DELETE'),
                        ],
                        max_length=8,
                    ),
                ),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
