# Generated by Django 5.2.5 on 2025-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('constraintsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminrule',
            name='adminrule_has_scope',
        ),
        migrations.AddField(
            model_name='adminrule',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='adminrule',
            constraint=models.CheckConstraint(condition=models.Q(('is_global', True), ('room__isnull', False), ('slot__isnull', False), _connector='OR'), name='adminrule_has_scope'),
        ),
    ]
